apiVersion: v1
kind: Service
metadata:
  name: vote-service
spec:
  type: LoadBalancer # This makes the service accessible from the internet
  selector:
    app: vote
  ports:
  - port: 80
    targetPort: 80
